### ISSUE TITLE
Example data can't open 

### ISSUE THREAD

**Issue by LegionHXF** [swiss-territorial-data-lab/proj-qalidar#2]
I am very interested in your code, but the [sample data1](https://data.stdl.ch/proj-qalidar/clipped_swissSURFACE3D_2018/2547000_1211500.las) and [sample data2](https://data.stdl.ch/proj-qalidar/Neuchatel_2022/2547000_1211500.laz)link is no longer valid. Can you re-upload the sample data?

**Comment by acerioni** [comment]
Hi @LegionHXF,

sample data is back online!

Thanks for your interest,
Alessandro Cerioni
